### ISSUE TITLE
how put my game pad

### ISSUE THREAD

**Issue by tazopolis** [ckdur/PIUIO_Arduino#2]
I am really noob

I have a question

How to connect the wiring in the PIUIO USB controller to arduino uno
I installed the Turn IntoAPIUIO.bat correctly
and in the pc it was identified as piuio when I connect it

I just want to put my gamepad or dance pad and play

**Comment by RhythmLunatic** [comment]
Connect wires to the ports on the arduino Uno and start PIU Fiesta 2/Prime/etc

**Comment by tazopolis** [comment]
> 

> Connect wires to the ports on the arduino Uno and start PIU Fiesta 2/Prime/etc
>  
> Make sure you installed ArdPIUIno first


this is my doubt
how it is connected in the ports
I'm noob in this

and if it is installed correctly

you will have the connection schematic for the buttons in arduino

**Comment by RhythmLunatic** [comment]
I think it's pins A1-A5, 2-13
Buttons are shorted from ground to the pins
I never got it working myself, other than shorting ground to the wrong pin and having it press every single input at once. You can test in the PIU service menu (plug in a keyboard and press F1 and F2 to navigate the menu)

**Comment by tazopolis** [comment]
> I never got it working myself, other than shorting ground to the wrong pin and having it press every single input at once. You can test in the PIU service menu (plug in a keyboard and press F1 and F2 to navigate the menu)


I tried like this
 it gives me the same problem all the sensors are pressed at the same time

I tried the GND-A1 without result
GND-TX presses everything
GND-8 without resolution
GND-RX presses everything

Is any resistance needed?

**Comment by tazopolis** [comment]
this not work :(
